# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=20)),
                ('servidor_smtp', models.CharField(max_length=250)),
                ('puerto_smtp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=240)),
                ('fecha_envio', models.DateTimeField()),
                ('enviado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_mensaje', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio.Mensaje'),
        ),
    ]
